//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
    
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            this.Configuration.LazyLoadingEnabled = false;
            throw new UnintentionalCodeFirstException();
        }
    
        public  DbSet<salt> salts { get; set; }
        public  DbSet<user> users { get; set; }
        public  DbSet<usersNotesData> usersNotesDatas { get; set; }
        public  DbSet<usersPasswordsData> usersPasswordsDatas { get; set; }
    }
}
