//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProjectClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.usersNotesDatas = new HashSet<usersNotesData>();
            this.usersPasswordsDatas = new HashSet<usersPasswordsData>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string pwdhash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<usersNotesData> usersNotesDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<usersPasswordsData> usersPasswordsDatas { get; set; }
        public override string ToString()
        {
            string oString = $"id = {this.id}\n email = {this.email} \n pwdhash = {this.pwdhash}\n userPasswordDatas = {this.usersPasswordsDatas} \n userNotesDatas = {this.usersNotesDatas}";
            return oString;
        }
    }
}
